### ISSUE TITLE
Internationalization in SignUpButton component

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace#61]
For some reason the internationalization for the SignUpButton text isn't changing to Spanish when I use the pageTitles.signup. It changes language when I use pageTitles.signup, but then the capitalization isn't the way I want it.

**Comment by r-southworth** [comment]
Expected behavior for pageTitles.signUp is for it ti be capitalized (Spanish should return `Registrarse`. If you want lower case then you probably want 'buttons.signUp' which will return `inscribirse`. Will make note with Tomas to check which word is more accurate - probably should be the same word for both just one with capital one without. 

There was an error in the spanish language file with the key name - somehow the capitalization was wrong so that is resolved.
